// Generated by gencpp from file tod/CoData.msg
// DO NOT EDIT!


#ifndef TOD_MESSAGE_CODATA_H
#define TOD_MESSAGE_CODATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>

namespace tod
{
template <class ContainerAllocator>
struct CoData_
{
  typedef CoData_<ContainerAllocator> Type;

  CoData_()
    : data()
    , msglabel()
    , sceneid(0)
    , imgid(0)  {
    }
  CoData_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , msglabel(_alloc)
    , sceneid(0)
    , imgid(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _data_type;
  _data_type data;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msglabel_type;
  _msglabel_type msglabel;

   typedef int16_t _sceneid_type;
  _sceneid_type sceneid;

   typedef int16_t _imgid_type;
  _imgid_type imgid;





  typedef boost::shared_ptr< ::tod::CoData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tod::CoData_<ContainerAllocator> const> ConstPtr;

}; // struct CoData_

typedef ::tod::CoData_<std::allocator<void> > CoData;

typedef boost::shared_ptr< ::tod::CoData > CoDataPtr;
typedef boost::shared_ptr< ::tod::CoData const> CoDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tod::CoData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tod::CoData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tod

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'tod': ['/home/robotxf/TOD_python/TOD_ros/src/tod/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tod::CoData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tod::CoData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tod::CoData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tod::CoData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tod::CoData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tod::CoData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tod::CoData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ceef3e91fd77e2286be70524a958bbe2";
  }

  static const char* value(const ::tod::CoData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xceef3e91fd77e228ULL;
  static const uint64_t static_value2 = 0x6be70524a958bbe2ULL;
};

template<class ContainerAllocator>
struct DataType< ::tod::CoData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tod/CoData";
  }

  static const char* value(const ::tod::CoData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tod::CoData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Data Structure for Saving Coproducts\n\
\n\
std_msgs/Float32MultiArray data\n\
string msglabel\n\
int16 sceneid\n\
int16 imgid\n\
================================================================================\n\
MSG: std_msgs/Float32MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
float32[]         data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::tod::CoData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tod::CoData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.msglabel);
      stream.next(m.sceneid);
      stream.next(m.imgid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tod::CoData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tod::CoData_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
    s << indent << "msglabel: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msglabel);
    s << indent << "sceneid: ";
    Printer<int16_t>::stream(s, indent + "  ", v.sceneid);
    s << indent << "imgid: ";
    Printer<int16_t>::stream(s, indent + "  ", v.imgid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOD_MESSAGE_CODATA_H
