// Generated by gencpp from file tod/ReqImageRequest.msg
// DO NOT EDIT!


#ifndef TOD_MESSAGE_REQIMAGEREQUEST_H
#define TOD_MESSAGE_REQIMAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tod
{
template <class ContainerAllocator>
struct ReqImageRequest_
{
  typedef ReqImageRequest_<ContainerAllocator> Type;

  ReqImageRequest_()
    : req(false)  {
    }
  ReqImageRequest_(const ContainerAllocator& _alloc)
    : req(false)  {
  (void)_alloc;
    }



   typedef uint8_t _req_type;
  _req_type req;





  typedef boost::shared_ptr< ::tod::ReqImageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tod::ReqImageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReqImageRequest_

typedef ::tod::ReqImageRequest_<std::allocator<void> > ReqImageRequest;

typedef boost::shared_ptr< ::tod::ReqImageRequest > ReqImageRequestPtr;
typedef boost::shared_ptr< ::tod::ReqImageRequest const> ReqImageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tod::ReqImageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tod::ReqImageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tod

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'tod': ['/home/robotxf/TOD_python/TOD_ros/src/tod/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tod::ReqImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tod::ReqImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tod::ReqImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tod::ReqImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tod::ReqImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tod::ReqImageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tod::ReqImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be3c44e19d0c6b00b25e356c69155e2a";
  }

  static const char* value(const ::tod::ReqImageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe3c44e19d0c6b00ULL;
  static const uint64_t static_value2 = 0xb25e356c69155e2aULL;
};

template<class ContainerAllocator>
struct DataType< ::tod::ReqImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tod/ReqImageRequest";
  }

  static const char* value(const ::tod::ReqImageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tod::ReqImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool req\n\
";
  }

  static const char* value(const ::tod::ReqImageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tod::ReqImageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReqImageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tod::ReqImageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tod::ReqImageRequest_<ContainerAllocator>& v)
  {
    s << indent << "req: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOD_MESSAGE_REQIMAGEREQUEST_H
