// Generated by gencpp from file tod/StartEval.msg
// DO NOT EDIT!


#ifndef TOD_MESSAGE_STARTEVAL_H
#define TOD_MESSAGE_STARTEVAL_H

#include <ros/service_traits.h>


#include <tod/StartEvalRequest.h>
#include <tod/StartEvalResponse.h>


namespace tod
{

struct StartEval
{

typedef StartEvalRequest Request;
typedef StartEvalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartEval
} // namespace tod


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tod::StartEval > {
  static const char* value()
  {
    return "93d7245f95bf423437148710b6b287c7";
  }

  static const char* value(const ::tod::StartEval&) { return value(); }
};

template<>
struct DataType< ::tod::StartEval > {
  static const char* value()
  {
    return "tod/StartEval";
  }

  static const char* value(const ::tod::StartEval&) { return value(); }
};


// service_traits::MD5Sum< ::tod::StartEvalRequest> should match 
// service_traits::MD5Sum< ::tod::StartEval > 
template<>
struct MD5Sum< ::tod::StartEvalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tod::StartEval >::value();
  }
  static const char* value(const ::tod::StartEvalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tod::StartEvalRequest> should match 
// service_traits::DataType< ::tod::StartEval > 
template<>
struct DataType< ::tod::StartEvalRequest>
{
  static const char* value()
  {
    return DataType< ::tod::StartEval >::value();
  }
  static const char* value(const ::tod::StartEvalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tod::StartEvalResponse> should match 
// service_traits::MD5Sum< ::tod::StartEval > 
template<>
struct MD5Sum< ::tod::StartEvalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tod::StartEval >::value();
  }
  static const char* value(const ::tod::StartEvalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tod::StartEvalResponse> should match 
// service_traits::DataType< ::tod::StartEval > 
template<>
struct DataType< ::tod::StartEvalResponse>
{
  static const char* value()
  {
    return DataType< ::tod::StartEval >::value();
  }
  static const char* value(const ::tod::StartEvalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOD_MESSAGE_STARTEVAL_H
