// Generated by gencpp from file tod/StartEvalRequest.msg
// DO NOT EDIT!


#ifndef TOD_MESSAGE_STARTEVALREQUEST_H
#define TOD_MESSAGE_STARTEVALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tod
{
template <class ContainerAllocator>
struct StartEvalRequest_
{
  typedef StartEvalRequest_<ContainerAllocator> Type;

  StartEvalRequest_()
    : start(false)  {
    }
  StartEvalRequest_(const ContainerAllocator& _alloc)
    : start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::tod::StartEvalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tod::StartEvalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartEvalRequest_

typedef ::tod::StartEvalRequest_<std::allocator<void> > StartEvalRequest;

typedef boost::shared_ptr< ::tod::StartEvalRequest > StartEvalRequestPtr;
typedef boost::shared_ptr< ::tod::StartEvalRequest const> StartEvalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tod::StartEvalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tod::StartEvalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tod

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'tod': ['/home/robotxf/TOD_python/TOD_ros/src/tod/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tod::StartEvalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tod::StartEvalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tod::StartEvalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tod::StartEvalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tod::StartEvalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tod::StartEvalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tod::StartEvalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::tod::StartEvalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676aa7bfb3ec2071ULL;
  static const uint64_t static_value2 = 0xe814f2368dfd5fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::tod::StartEvalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tod/StartEvalRequest";
  }

  static const char* value(const ::tod::StartEvalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tod::StartEvalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start\n\
";
  }

  static const char* value(const ::tod::StartEvalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tod::StartEvalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartEvalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tod::StartEvalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tod::StartEvalRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOD_MESSAGE_STARTEVALREQUEST_H
